### PR TITLE
tuning up scripts for CentOS7 Ubuntu14/12

### PR DESCRIPTION
**Pull request by belimor**

### CODE REVIEW

**Comment by Chealion** [comment]
Supposed to be against the cybera:rac branch?

**Comment by belimor** [comment]
Possibly. Do we have the same repo at cybera account?

**Comment by Chealion** [comment]
Yes - https://github.com/cybera/openstack-images/tree/rac

I think the changes you made were already put into the rac branch (but without a separate CentOS file). If you can confirm we can close the issue here and you or I can migrate the changes from rac to the master branch.

**Comment by belimor** [comment]
Close it here. I will resubmit request to cybera repo if necessary

**Comment by Chealion** [comment]
:+1:

**Pull request closed without merging**
